bash ./scripts/train.sh eurosat color_crop_cutout_flip_scale_rotate
bash ./scripts/train.sh dtd color
bash ./scripts/train.sh fgvc_aircraft color
bash ./scripts/train.sh stanford_cars color
bash ./scripts/train.sh btmri color_crop_cutout_flip_scale_rotate
bash ./scripts/train.sh ccbtm color
bash ./scripts/train.sh chmnist color
bash ./scripts/train.sh resisc45 color
bash ./scripts/train.sh patternnet color
bash ./scripts/train.sh mlrsnet color
bash ./scripts/train.sh rsicd color